# Project  information
site_name: Awesome Web Development
site_description: A curated list of impressive framework, libraries, software and resources for your project on web development.
site_author: Andrick Santos
site_url: https://andricksantos.github.io/awesome-web-development/

# Repository
repo_name: andricksantos/awesome-web-development
repo_url: https://github.com/andricksantos/awesome-web-development
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 Andrick Santos'

pages:
  - Life is short, you need programer: index.md
theme: material

# Customization
extra:
  social:
    - type: globe
      link: https://andricksantos.github.io/
    - type: github-alt
      link: https://github.com/andricksantos
    - type: twitter
      link: https://twitter.com/santosandrick1
    - type: linkedin
      link: https://www.linkedin.com/in/andrick-santos-19128b146/
    - type: facebook
      link: https://www.facebook.com/andrick.mago
    - type: instagram
      link: https://www.instagram.com/andricksantos12/
    - type: youtube
      link: https://www.youtube.com/channel/UCepbBv6NUBPnPAJyZqSiWWQ?sub_confirmation=1
      
# Google Analytics
google_analytics:
  - 'UA-103804510-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true